import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
const root=path.resolve(import.meta.dirname,'..');
let source=fs.readFileSync(path.join(root,'src/main.js'),'utf8');
const importEnd=source.indexOf('const A=');
source=source.slice(0,importEnd)+'\n(async()=>{\n'+source.slice(importEnd)+'\n})().catch(e=>{console.error(e);const l=document.getElementById("loading");l.classList.remove("hide");l.textContent="初始化失败："+e.message;});';
const result=await build({stdin:{contents:source,resolveDir:path.join(root,'src'),sourcefile:'main.js',loader:'js'},bundle:true,format:'iife',target:'es2022',minify:true,write:false,legalComments:'inline'});
let old=fs.readFileSync(path.join(root,'src/shell.html'),'utf8');
let html=old;
html=html.replace('<title>土星 · SATURN OBSERVATORY</title>','<title>土星 · SATURN OBSERVATORY III</title>');
const views=['classic','wide','cloud','ring','edge','atmos','backlit'];const scenes=['hex','titan','enceladus','mimas','aurora'];
html=html.replace(/data-view="(\d)"/g,(_,i)=>`data-shot="${views[+i]}"`).replace(/data-scene="(\d)"/g,(_,i)=>`data-shot="${scenes[+i-1]}"`);
html=html.replace('<button class="back" id="back">','<button class="scene-btn" data-shot="cassini" aria-pressed="false">卡西尼—惠更斯<span>06 ↗</span></button><select id="moonSelect" aria-label="前往其他卫星"><option value="">其他卫星 · 19 颗</option></select><button class="back" id="back">');
html=html.replace('<div class="badge chrome" id="viewCaption">','<button id="iceDive" class="chrome" hidden>下潜至冰粒之间 ↓</button><div class="badge chrome" id="viewCaption">');
html=html.replace('<span class="hint">拖动环绕 · 滚轮缩放 · 双击复位</span>','<span class="hint">镜头距离 <span id="range">—</span></span>');
html=html.replace('>转速</label>','>时间</label>').replace('>1×</output>','>120×</output>').replace('>自转中</span>','>运行中</span>');
html=html.replace('<span class="toggle"></span>银河</button>','<span class="toggle"></span>银河</button><button id="labelsToggle" class="control" aria-pressed="false">卫星标记</button>');
html=html.replace('<div id="toast" role="status">','<div id="labels"></div><div id="travel"><span>正在飞往观测点</span><i id="travelFill"></i></div><div id="toast" role="status">');
html=html.replace(/<dialog id="about">[\s\S]*?<\/dialog>/,`<dialog id="about"><button id="closeInfo" aria-label="关闭说明">关闭</button><h2>土星观测站 · 第三版</h2>
<p>所有镜头使用同一个三维空间。卫星和卡西尼可自由环绕，缩放保留安全范围；土星近景及环面镜头仍限定角度。大气仰望允许绕当地竖直方向旋转，视线限制在半顶角 80° 的圆锥内。星环特写直接抵达不规则冰块之间。无遮挡飞行采用直达路径，遇到天体才沿其外侧切线绕行；接近米级目标时逐渐减速。</p>
<p><strong>尺度与方向</strong>：土星赤道半径 60,268 km，极半径 54,364 km。环面与赤道共面；26.73° 是自转轴相对公转轨道法线的倾角，不是星环相对赤道的倾斜。D、C、B、A、F 环及卡西尼缝、恩克缝、基勒缝依据 NASA 尺寸设置。A 环外缘 136,780 km，F 环约 139,826 km。</p>
<p><strong>历史空间布局</strong>：卡西尼及 19 颗主要卫星的坐标来自 JPL Horizons，历元为 2004-07-01 02:39 UTC。此时卡西尼已被土星捕获并接近首次入轨近土点。卫星和探测器保持这一历史位置；“时间”调节云层自转、环粒共轨差速和气体现象的演示速度，不代表完整任务星历回放。小卫星不会为可见性而放大，可用标记或右侧列表前往。太阳照明采用初版的北半球受光构图方向，因此太阳方向不代表该历史历元。</p>
<p><strong>真实素材</strong>：卡西尼—惠更斯模型、土星模型和贴图、泰坦、土卫二、米玛斯纹理来自 NASA VTAD。其余小卫星使用真实半径与位置，表面纹理由冰质地貌示意，并非逐颗卫星的实测地图。探测器及卫星表面的朝向用于展示，没有重建历史姿态遥测。</p>
<p><strong>星环与发光现象</strong>：近景会自动显示 D、C、B、A、F 环以及主要缝隙的结构标注。主环主要为水冰，含少量尘埃杂质；近距采用 0.2–6 m 的冰粒样本，薄层厚度约 20 m，并按开普勒差速展示相对运动。远处按光学深度显示连续环带，不把冰块放大到行星尺度。极光常驻在两极，使用粉红至紫色弱发光，典型高度控制在数百至约 1,500 km；极光镜头略提高曝光。大气边缘和逆光效果按散射路径近似计算，太阳辉光及少量镜头光晕属于曝光表现。土卫二喷流为南极数十至约 200 km 的稀薄冰粒喷束示意，不把更远处、肉眼不可见的水汽云画成明亮光柱。</p>
<p><strong>大气仰望</strong>：以纪录片中的土星大气模拟画面为构图参考，加入有体积的金色云顶、天际线薄雾和同一三维星环的实际天空投影。云形和散射是艺术重建，不是探测器拍摄的原始画面；星空银河为程序背景。所有材质和依赖均嵌入本文件，可离线打开。</p>
<p>资料：<a href="https://nssdc.gsfc.nasa.gov/planetary/factsheet/saturnfact.html" target="_blank" rel="noopener">NASA 土星尺寸</a> / <a href="https://nssdc.gsfc.nasa.gov/planetary/factsheet/satringfact.html" target="_blank" rel="noopener">NASA 星环参数</a> / <a href="https://ssd.jpl.nasa.gov/horizons/" target="_blank" rel="noopener">JPL Horizons</a> / <a href="https://science.nasa.gov/resource/cassini-3d-model/" target="_blank" rel="noopener">NASA 卡西尼模型</a> / <a href="https://www.nasa.gov/wp-content/uploads/2015/01/61369main_soitimeline.pdf" target="_blank" rel="noopener">入轨时间表</a> / <a href="https://arxiv.org/abs/1506.00664" target="_blank" rel="noopener">土星可见光极光研究</a></p><details><summary>观测数据与镜头状态</summary><pre id="diagnostics"></pre></details></dialog>`);
html=html.replace('</style>',`#universe:focus{outline:none}.rail{z-index:5}.right{width:170px}.scene-btn{padding:12px 7px;background:#06090c4d}.left{background:linear-gradient(90deg,#06090c6b,transparent);padding-right:12px}.footer{z-index:7}.views{z-index:7;max-width:calc(100% - 450px)}#moonSelect{width:100%;margin-top:15px;padding:9px 4px;background:#11151cb0}.moon-tag{position:fixed;border:0;color:#d3c7ac;background:#06090b8c;padding:4px 8px;font-size:9px;transform:translate(8px,-50%);z-index:2}.moon-tag:before{content:'·';margin-right:5px;color:#f0d2a3}.moon-tag[hidden]{display:none}#travel{position:fixed;top:97px;left:50%;transform:translateX(-50%);width:180px;text-align:center;color:#baa788;font-size:10px;letter-spacing:2px;opacity:0;transition:opacity .3s;z-index:8}#travel.show{opacity:1}#travel i{display:block;height:1px;background:#d7b987;transform-origin:left;margin-top:10px}#iceDive{position:fixed;left:50%;transform:translateX(-50%);bottom:180px;padding:10px 20px;border:1px solid #c2a1705c;background:#090d13b0;border-radius:5px;color:#d7b987;z-index:7;font-size:11px}.badge{white-space:nowrap}#diagnostics{white-space:pre-wrap;font:11px Consolas;line-height:1.6}.clean #labels,.clean #travel{display:none}.intro h1{font-size:45px}.top,.intro,.badge{text-shadow:0 2px 8px #0008}.loading{z-index:30}@media(max-width:1100px){.views{max-width:calc(100% - 40px)}.right{width:138px}}@media(max-width:650px){.right{width:106px;right:10px}.rail{top:40%}.scene-btn{padding:10px 3px;font-size:9px}#moonSelect{font-size:9px}.left{left:10px;width:85px}.views{max-width:calc(100% - 28px)}#iceDive{bottom:210px}.badge{font-size:8px;max-width:95vw;white-space:normal;text-align:center;width:max-content}#labelsToggle{font-size:9px}.intro{display:none!important}.controls{gap:8px}.footer{left:12px;right:12px}.top{left:12px;right:12px}.wordmark{font-size:9px}.scene-label{max-width:48%}#sceneName{font-size:12px}.subbrand{font-size:7px}}
</style>`);

html=html.replace(/<button[^>]*data-style="[24]"[\s\S]*?<\/button>/g,'').replace('线框','辉光素描').replace('ORBITAL STUDY','LUMINOUS CONTOURS');
html=html.replace('<div id="labels">',`<aside id="ringGuide" class="chrome" aria-label="星环结构"><div id="ringLocation">主环结构</div><svg viewBox="0 0 450 58" aria-label="D C B A F 环及卡西尼缝、恩克缝、基勒缝"><g fill="#d8c29b"><rect x="6" y="22" width="47" height="5" opacity=".15"/><rect x="54" y="22" width="105" height="5" opacity=".4"/><rect x="159" y="22" width="153" height="5" opacity=".9"/><rect x="341" y="22" width="86" height="5" opacity=".7"/><rect x="445" y="21" width="1.5" height="7"/></g><g fill="#13171b"><rect x="407" y="21" width="2" height="7"/><rect x="425" y="21" width="1" height="7"/></g><g fill="#b9b1a5" font-size="10" text-anchor="middle"><text x="29" y="15">D</text><text x="105" y="15">C</text><text x="235" y="15">B</text><text x="371" y="15">A</text><text x="445" y="15">F</text><text x="326" y="43">卡西尼缝</text><text x="402" y="43">恩克缝</text><text x="429" y="57">基勒缝</text></g></svg></aside><div id="labels">`);
html=html.replace('</style>',`#ringGuide{position:fixed;left:50%;top:112px;transform:translateX(-50%);width:430px;padding:10px 16px;background:linear-gradient(110deg,#080c12cf,#080c1255);border:1px solid #c2aa7722;border-radius:7px;opacity:0;pointer-events:none;transition:opacity .7s;z-index:4}#ringGuide.show{opacity:1}#ringLocation{font:10px 'Microsoft YaHei',sans-serif;color:#c9b796;letter-spacing:1px;margin-bottom:5px}#ringGuide svg{width:100%;height:54px;display:block}.style-btn{margin-bottom:18px}.s3{background:radial-gradient(ellipse at 30% 25%,#82bfc8,#143d47 45%,#060f19 75%)}@media(max-width:650px){#ringGuide{top:122px;width:260px;padding:8px 10px}#ringGuide svg{height:43px}#ringLocation{font-size:8px}.style-btn{margin-bottom:12px}}.clean #ringGuide{display:none}</style>`);

html+='<script id="assets" type="application/json">'+fs.readFileSync(path.join(root,'assets/embedded.json'),'utf8').replaceAll('</','<\\/')+'</script>\n<script>'+result.outputFiles[0].text.replaceAll('</script','<\\/script')+'</script></body></html>';
const notices=fs.readFileSync(path.join(root,'THIRD_PARTY_NOTICES.md'),'utf8');
const license=fs.readFileSync(path.join(root,'LICENSE'),'utf8');
html=html.replace('</head>','<meta name="description" content="土星观测站：可离线使用的交互式三维土星、星环、卫星与卡西尼探测器可视化。"></head>');
html=html.replace('<details><summary>观测数据与镜头状态</summary>', '<p>独立的 AI 辅助开发可视化项目，未经 NASA/JPL 审核或背书。公开资料用于模型与数据参考，渲染结果属于本项目的演示重建。第三方署名与许可全文保留在本文件源代码及项目 THIRD_PARTY_NOTICES.md 中。</p><details><summary>观测数据与镜头状态</summary>');
html=html.replace('</body>', '<!--\n'+(license+'\n\n'+notices).replaceAll('--','—')+'\n--></body>');
fs.writeFileSync(path.join(root,'index.html'),html);
console.log('Built index.html:',Buffer.byteLength(html),'bytes');
