import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {planRoute,flightDistance,orientation,coneDirection,ease} from './navigation.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const A=JSON.parse(document.getElementById('assets').textContent),$=id=>document.getElementById(id);
const R=60268,RP=54364,MU=37931000,TAU=Math.PI*2,DEG=Math.PI/180;
const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),clamp=THREE.MathUtils.clamp,mix=THREE.MathUtils.lerp;
const ep=A.ephemeris,Sun=V(-.619,.433,.655).normalize(),zero=V();
const state={style:0,oldStyle:0,styleBlend:1,scene:'classic',playing:true,time:0,speed:120,galaxy:true,quality:1.5,labels:false,yaw:0,pitch:0,zoom:1,transit:null};
const renderer=new THREE.WebGLRenderer({canvas:$('universe'),antialias:true,alpha:false,logarithmicDepthBuffer:true,powerPreference:'high-performance'});
renderer.autoClear=false;renderer.outputColorSpace=THREE.LinearSRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.000001,3e8);
const eye=V(),look=V(),up=V(0,1,0),worldObjects=[],surfaceMaterials=[],uniformsToUpdate=[];
const light=new THREE.DirectionalLight(0xfff2dc,3.2);scene.add(light,light.target);scene.add(new THREE.HemisphereLight(0xbac9dc,0x746a51,.045));
const pmrem=new THREE.PMREMGenerator(renderer);const env=pmrem.fromScene(new RoomEnvironment(),.03).texture;
const texLoader=new THREE.TextureLoader(),loader=new GLTFLoader();
function texture(url){const t=texLoader.load(url);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return t;}
async function model(url){const raw=Uint8Array.from(atob(url.split(',')[1]),c=>c.charCodeAt(0));return (await loader.parseAsync(raw.buffer,'')).scene;}
function anchored(object,position){worldObjects.push({object,position:position.clone()});scene.add(object);return object;}
const common=`
float hash3(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}
float n3(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash3(i),hash3(i+vec3(1,0,0)),f.x),mix(hash3(i+vec3(0,1,0)),hash3(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash3(i+vec3(0,0,1)),hash3(i+vec3(1,0,1)),f.x),mix(hash3(i+vec3(0,1,1)),hash3(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm3(vec3 p){float n=0.,a=.5;for(int i=0;i<4;i++){n+=n3(p)*a;p=p*2.07+13.4;a*=.5;}return n;}
float sphShadow(vec3 p,vec3 d,vec3 axes){vec3 o=p/axes,v=d/axes;float b=dot(o,v),a=dot(v,v),c=dot(o,o)-1.;float h=b*b-a*c;if(h<0.)return 1.;return (-b-sqrt(h))/a>0.?0.:1.;}
`;
// A radial optical-depth profile in physical kilometres, with documented ring boundaries.
function ringProfile(){const w=16384,data=new Uint8Array(w*4);let seed=71;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};let smooth=.5;
 for(let i=0;i<w;i++){const r=65000+(145000-65000)*i/(w-1);smooth=mix(smooth,rand(),.14);let tau=0,b=.5;
 if(r>=66900&&r<74510){tau=.00001;b=.2;}if(r>=74658&&r<91975){tau=.07+.19*smooth;b=.34;}
 if(r>=91975&&r<117507){tau=.7+1.5*smooth+.25*Math.sin(r*.013);b=.72;}
 if(r>=117507&&r<122340){tau=.006+.035*smooth;b=.38;}
 if(r>=122340&&r<136780){tau=.43+.43*smooth;b=.66;}
 if(Math.abs(r-133584)<162)tau=.001;if(Math.abs(r-136505)<21)tau=.0001;
 if(Math.abs(r-139826)<35){tau=.15;b=.80;}else if(Math.abs(r-139826)<180){tau=.007;b=.65;}
 // Fine opaque ringlets and density waves ride on the measured optical-depth bands.
 tau*=.88+.12*Math.sin(r*.19)+.045*Math.sin(r*.97);b*=(.66+.28*smooth)*(.92+.08*Math.sin(r*.024)+.045*Math.sin(r*.17));
 data[i*4]=Math.round(255*b);data[i*4+1]=Math.round(255*b*.94);data[i*4+2]=Math.round(255*b*.83);data[i*4+3]=Math.round(255*clamp(tau/3,0,1));}
 const t=new THREE.DataTexture(data,w,1,THREE.RGBAFormat);t.needsUpdate=true;t.generateMipmaps=true;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;return t;}
const ringsTex=ringProfile();
function enhancePlanet(mat,kind){mat.metalness=0;mat.roughness=1;mat.color.setScalar(kind==='saturn'?.93:1);mat.onBeforeCompile=s=>{
 Object.assign(s.uniforms,{uWorldEye:{value:eye},uSun:{value:Sun},uRing:{value:ringsTex},uKind:{value:kind==='saturn'?0:1},uSimTime:{value:0}});
 s.vertexShader='varying vec3 vAbsLocal;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nvAbsLocal=(modelMatrix*vec4(transformed,1.)).xyz;');
 s.fragmentShader='varying vec3 vAbsLocal;uniform vec3 uWorldEye,uSun;uniform sampler2D uRing;uniform int uKind;uniform float uSimTime;\n'+common+s.fragmentShader;
 s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
 if(uKind==0){vec3 p=(vAbsLocal+uWorldEye)/60268.;float fine=fbm3(vec3(p.x*130.,p.y*310.,p.z*130.));diffuseColor.rgb*=.94+.12*fine;
 float lat=p.y/.90204;float a=atan(p.z,p.x)+uSimTime*.0001638;float rad=length(p.xz);float hx=rad*cos(mod(a+0.5235988,1.0471976)-0.5235988);float disturbance=(fbm3(vec3(p.x*110.,p.z*110.,3.))-.5)*.0025;float jet=exp(-pow((hx-.228+disturbance)/.010,2.));if(lat>.90){float inside=1.-smoothstep(.218,.244,hx);float whirl=a+1.6*exp(-rad*7.);vec3 w=vec3(cos(whirl)*rad*110.,sin(whirl)*rad*110.,rad*30.);float cloud=fbm3(w);diffuseColor.rgb=mix(diffuseColor.rgb,diffuseColor.rgb*vec3(.81,.98,1.04),inside*.55);diffuseColor.rgb*=1.-jet*.22;diffuseColor.rgb*=.94+cloud*.16;float eye=1.-smoothstep(.009,.023,rad);diffuseColor.rgb*=1.-eye*.50;float swirl=sin(rad*1100.+whirl*3.+cloud*7.)*exp(-rad*24.);diffuseColor.rgb*=1.+swirl*.06;}
 }`);
 s.fragmentShader=s.fragmentShader.replace('#include <lights_fragment_end>',`#include <lights_fragment_end>\nif(uKind==0){vec3 p=vAbsLocal+uWorldEye;float st=-p.y/uSun.y;if(st>0.){float rr=length((p+uSun*st).xz);if(rr>65000.&&rr<145000.){float tau=texture2D(uRing,vec2((rr-65000.)/80000.,.5)).a*3.;float transmission=exp(-tau/max(.06,abs(uSun.y)));reflectedLight.directDiffuse*=transmission;reflectedLight.directSpecular*=transmission;}}}`);uniformsToUpdate.push(s.uniforms);
 };mat.customProgramCacheKey=()=>kind;surfaceMaterials.push(mat);}
const saturnRoot=await model(A.saturn);let planetMesh=null;
saturnRoot.traverse(o=>{if(o.isMesh){o.geometry.computeBoundingBox();let size=o.geometry.boundingBox.getSize(V());if(size.y>100){planetMesh=o;}else o.visible=false;}});
if(!planetMesh)throw Error('NASA 土星模型未找到球体。');enhancePlanet(planetMesh.material,'saturn');saturnRoot.scale.setScalar(R/500);anchored(saturnRoot,zero);

// Subdivide the NASA atlas mesh while retaining its UV islands, then project onto the measured ellipsoid.
function smoothSaturn(original){let g=original.index?original.toNonIndexed():original.clone();for(let pass=0;pass<2;pass++){const p=g.attributes.position,u=g.attributes.uv,ps=[],us=[],ns=[];const vertex=i=>({p:V().fromBufferAttribute(p,i),u:new THREE.Vector2().fromBufferAttribute(u,i)});const mid=(a,b)=>({p:a.p.clone().add(b.p).multiplyScalar(.5),u:a.u.clone().add(b.u).multiplyScalar(.5)});function push(v){const q=v.p.clone();q.multiplyScalar(1/Math.sqrt((q.x/500)**2+(q.y/451.019)**2+(q.z/500)**2));ps.push(...q.toArray());us.push(v.u.x,v.u.y);ns.push(...V(q.x/250000,q.y/(451.019**2),q.z/250000).normalize().toArray());}for(let i=0;i<p.count;i+=3){const a=vertex(i),b=vertex(i+1),c=vertex(i+2),ab=mid(a,b),bc=mid(b,c),ca=mid(c,a);[a,ab,ca,ab,b,bc,ca,bc,c,ab,bc,ca].forEach(push);}g.dispose();g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(ps,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(ns,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(us,2));}return g;}
planetMesh.geometry=smoothSaturn(planetMesh.geometry);

const ringGeometry=new THREE.RingGeometry(65000,145000,1024,1);ringGeometry.rotateX(-Math.PI/2);
const ringUniform={uEye:{value:eye},uSun:{value:Sun},uRing:{value:ringsTex},uPatch:{value:V(1e8,0,0)},uHole:{value:0},uStyle:{value:0}};
const ringMaterial=new THREE.ShaderMaterial({uniforms:ringUniform,transparent:true,side:THREE.DoubleSide,depthWrite:false,vertexShader:`varying vec3 vP;#include <logdepthbuf_pars_vertex>
void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);#include <logdepthbuf_vertex>}`,fragmentShader:`precision highp float;varying vec3 vP;uniform vec3 uEye,uSun,uPatch;uniform sampler2D uRing;uniform float uHole;${common}
#include <logdepthbuf_pars_fragment>
void main(){#include <logdepthbuf_fragment>
float r=length(vP.xz);vec4 band=texture2D(uRing,vec2((r-65000.)/80000.,.5));float tau=band.a*3.;float mu=max(.015,abs(normalize(uEye-vP).y));float alpha=1.-exp(-tau/mu);if(alpha<.0005)discard;
float sh=sphShadow(vP+uSun*.1,uSun,vec3(60268.,54364.,60268.));float illum=.024+sh*(.24+abs(uSun.y)*.85);float phase=pow(max(0.,dot(normalize(vP-uEye),uSun)),8.);vec3 c=band.rgb*illum*(1.+phase*.4);
if(uHole>0.){float d=length(vP-uPatch);alpha*=mix(1.,smoothstep(1.5,2.0,d),uHole);alpha*=smoothstep(.3,2.,length(uEye-uPatch));}
gl_FragColor=vec4(c,alpha);}`.replaceAll(';#include',';\n#include').replaceAll('{#include','{\n#include')});
ringMaterial.vertexShader=ringMaterial.vertexShader.replaceAll(';#include',';\n#include');const rings=anchored(new THREE.Mesh(ringGeometry,ringMaterial),zero);rings.renderOrder=3;
// The faint E and G rings are retained at low optical depth, never a bright extra disc.
const dustMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{uSun:{value:Sun}},vertexShader:`varying vec3 vP;#include <logdepthbuf_pars_vertex>
void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);#include <logdepthbuf_vertex>}`.replaceAll(';#include',';\n#include'),fragmentShader:`varying vec3 vP;#include <logdepthbuf_pars_fragment>
void main(){#include <logdepthbuf_fragment>
float r=length(vP.xz);float d=exp(-pow((r-238000.)/70000.,2.))*.00001+exp(-pow((r-169000.)/2000.,2.))*.00001;gl_FragColor=vec4(.22,.26,.3,d);}`.replaceAll(';#include',';\n#include').replaceAll('{#include','{\n#include')});let dg=new THREE.RingGeometry(166000,480000,256);dg.rotateX(-Math.PI/2);anchored(new THREE.Mesh(dg,dustMat),zero).renderOrder=4;
// Atmosphere shells use actual radial heights, with no bright oversized halo.
function shell(radius,flatten,center,color,depth=.20){const m=new THREE.ShaderMaterial({transparent:true,side:THREE.BackSide,depthWrite:false,uniforms:{uSun:{value:Sun},uColor:{value:new THREE.Color(color)},uDepth:{value:depth}},vertexShader:`varying vec3 vN,vV;#include <logdepthbuf_pars_vertex>
void main(){vec4 p=modelViewMatrix*vec4(position,1.);vV=normalize(-p.xyz);vN=normalize(normalMatrix*normal);gl_Position=projectionMatrix*p;#include <logdepthbuf_vertex>}`.replaceAll(';#include',';\n#include'),fragmentShader:`varying vec3 vN,vV;uniform vec3 uColor;uniform float uDepth;#include <logdepthbuf_pars_fragment>
void main(){#include <logdepthbuf_fragment>
float f=pow(1.-abs(dot(normalize(vN),normalize(vV))),3.);gl_FragColor=vec4(uColor,4.*f*(1.-f)*uDepth);}`.replaceAll(';#include',';\n#include').replaceAll('{#include','{\n#include')});let o=new THREE.Mesh(new THREE.SphereGeometry(radius,96,64),m);o.scale.y=flatten;o.renderOrder=2;return anchored(o,center);}
shell(R+150,(RP+150)/(R+150),zero,0x897b60,.17);
// Real body radii, with positions from one coherent JPL Horizons epoch.
const moonSpecs=[['mimas','米玛斯',198.2],['enceladus','恩克拉多斯',252.1],['tethys','忒堤斯',531.1],['dione','狄俄涅',561.4],['rhea','瑞亚',763.8],['titan','泰坦',2574.7],['hyperion','许珀里翁',135],['iapetus','伊阿珀托斯',734.5],['phoebe','菲比',106.5],['janus','雅努斯',89.5],['epimetheus','厄庇墨透斯',58.1],['helene','海伦',17.6],['telesto','忒勒斯托',12.4],['calypso','卡吕普索',10.7],['atlas','阿特拉斯',15.1],['prometheus','普罗米修斯',43.1],['pandora','潘多拉',40.7],['pan','潘',14.1],['daphnis','达芙妮',3.8]];
const bodies={};const grayMap=texture(A.enceladus0);
for(const [id,name,radius] of moonSpecs){const position=V(...ep[id].position);let object;if(id==='mimas'){object=await model(A.mimas);object.updateMatrixWorld(true);const size=new THREE.Box3().setFromObject(object).getSize(V());object.scale.multiplyScalar(radius*2/Math.max(size.x,size.y,size.z));object.rotation.y=-2.74;object.traverse(o=>{if(o.isMesh){o.material.metalness=0;o.material.roughness=1;o.material.color.setScalar(.9);}});}else{
const map=id==='titan'?texture(A.titan0):grayMap;const mat=new THREE.MeshStandardMaterial({map,roughness:1,color:id==='titan'?0xc6924a:id==='enceladus'?0xf0f3f4:0xa6a49d});const geo=new THREE.SphereGeometry(radius,id==='titan'||id==='enceladus'?128:32,id==='titan'||id==='enceladus'?96:24);object=new THREE.Mesh(geo,mat);if(['hyperion','pan','atlas','prometheus','pandora'].includes(id))object.scale.set(1.3,.75,.95);
}anchored(object,position);bodies[id]={id,name,radius,position,object};if(id==='titan')shell(radius+60,1,position,0xab763b,.24);
const option=document.createElement('option');option.value=id;option.textContent=name;$('moonSelect').append(option);
}
// Permanent polar curtains: physical heights of hundreds to 1,500 km and pink/violet emission.
const auroraUniform={uTime:{value:0},uGain:{value:1}};
for(const sign of [-1,1]){const rows=16,cols=320,verts=[],uv=[],indices=[];for(let j=0;j<=rows;j++){const h=120+1380*j/rows;for(let i=0;i<=cols;i++){const a=i/cols*TAU;const lat=(74.5+1.1*Math.sin(a*5)+.6*Math.sin(a*13))*DEG;const rr=(R+h)*Math.cos(lat);verts.push(Math.cos(a)*rr,sign*(RP+h)*Math.sin(lat),Math.sin(a)*rr);uv.push(i/cols,j/rows);if(i<cols&&j<rows){let k=j*(cols+1)+i;indices.push(k,k+1,k+cols+1,k+1,k+cols+2,k+cols+1);}}}
const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);const m=new THREE.ShaderMaterial({uniforms:auroraUniform,transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,vertexShader:`varying vec2 vUv;#include <logdepthbuf_pars_vertex>
void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);#include <logdepthbuf_vertex>}`.replaceAll(';#include',';\n#include'),fragmentShader:`varying vec2 vUv;uniform float uTime,uGain;${common}
#include <logdepthbuf_pars_fragment>
void main(){#include <logdepthbuf_fragment>
float strand=.3+.7*pow(.5+.5*sin(vUv.x*820.+sin(vUv.x*75.+uTime*.1)*3.),3.);float top=.55+.3*n3(vec3(vUv.x*40.,uTime*.013,0.));float alpha=strand*(1.-smoothstep(.02,top,vUv.y))*smoothstep(0.,.1,vUv.y)*.06*uGain;vec3 col=mix(vec3(.58,.15,.28),vec3(.25,.13,.65),vUv.y);gl_FragColor=vec4(col,alpha);}`.replaceAll('{#include','{\n#include')});anchored(new THREE.Mesh(g,m),zero).renderOrder=5;}
// Thin individual south-polar jets, measured in km, continually present at Enceladus.
const jets=new THREE.Group();const plumeMaterials=[];for(let i=0;i<8;i++){const h=70+(i%4)*32;const a=i*.91;const radius=2.3;const g=new THREE.CylinderGeometry(12,.35,h,20,1,true);g.translate(0,h*.5,0);const m=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{uT:{value:0},uI:{value:i}},vertexShader:`varying vec2 vUv;#include <logdepthbuf_pars_vertex>
void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);#include <logdepthbuf_vertex>}`.replaceAll(';#include',';\n#include'),fragmentShader:`varying vec2 vUv;uniform float uT,uI;${common}
#include <logdepthbuf_pars_fragment>
void main(){#include <logdepthbuf_fragment>
float fade=pow(sin(vUv.y*3.14159),1.3);float str=.4+.6*n3(vec3(vUv.x*18.,vUv.y*22.-uT*.12,uI));gl_FragColor=vec4(.50,.57,.61,fade*str*.018);}`.replaceAll('{#include','{\n#include')});const jet=new THREE.Mesh(g,m);jet.rotation.z=Math.PI+(i-3.5)*.025;jet.position.set(Math.cos(a)*12,-251,Math.sin(a)*9);jets.add(jet);plumeMaterials.push(m);}
anchored(jets,bodies.enceladus.position).renderOrder=5;
// NASA's detailed Cassini-Huygens geometry is kept at metre scale, including the carried probe.
const cassini=await model(A.cassini);cassini.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(cassini);const dims=box.getSize(V());const center=box.getCenter(V());cassini.position.sub(center);const craft=new THREE.Group();craft.add(cassini);craft.scale.setScalar(.011/Math.max(dims.x,dims.y,dims.z));
cassini.traverse(o=>{if(o.isMesh){o.frustumCulled=false;o.material.envMap=env;o.material.envMapIntensity=.33;o.material.roughness=Math.max(.35,o.material.roughness||.5);}});const cassiniPos=V(...ep.cassini.position);anchored(craft,cassiniPos);craft.rotation.set(.2,-.7,.25);
// Locally resolved ring particles: 0.2–6 m ice bodies in a 10–30 m thick co-orbiting sheet.
const patch=V(129500,0,0),patchRadius=129500,orbitalN=Math.sqrt(MU/Math.pow(patchRadius,3));
const iceGeo=new THREE.IcosahedronGeometry(1,2);let pos=iceGeo.attributes.position;for(let i=0;i<pos.count;i++){let v=V().fromBufferAttribute(pos,i);v.multiplyScalar(.78+.24*Math.sin(v.x*29+v.y*17+v.z*11));pos.setXYZ(i,v.x,v.y,v.z);}iceGeo.computeVertexNormals();
const iceMat=new THREE.MeshStandardMaterial({color:0xc5cbd0,roughness:.77,metalness:.02,envMap:env,envMapIntensity:.035});
const iceCount=7600,ice=new THREE.InstancedMesh(iceGeo,iceMat,iceCount);ice.instanceMatrix.setUsage(THREE.DynamicDrawUsage);ice.frustumCulled=false;scene.add(ice);let seed=91232;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
const particles=[];for(let i=0;i<iceCount;i++){particles.push({x:(rand()-.5)*.85,y:(rand()-.5)*.020,z:(rand()-.5)*.85,size:.00010+Math.pow(rand(),5)*.0029,rot:rand()*TAU});const albedo=.55+rand()*.28;ice.setColorAt(i,new THREE.Color().setRGB(albedo*.95,albedo*.99,albedo));}
const dummy=new THREE.Object3D();function updateIce(){const distance=eye.distanceTo(patch),close=distance<150;ice.visible=close;ringUniform.uHole.value=1-THREE.MathUtils.smoothstep(distance,1.8,30);ringUniform.uPatch.value.copy(patch);if(!close)return;ice.position.copy(patch).sub(eye);for(let i=0;i<iceCount;i++){const p=particles[i];const dz=-1.5*orbitalN*p.x*state.time;let z=((p.z+dz+.425)%.85+.85)%.85-.425;dummy.position.set(p.x,p.y+Math.sin(state.time*.002+p.rot)*.0005,z);dummy.rotation.set(p.rot+state.time*.0002,p.rot*.4,p.rot*.7);dummy.scale.set(p.size,p.size*.73,p.size*1.11);dummy.updateMatrix();ice.setMatrixAt(i,dummy.matrix);}ice.instanceMatrix.needsUpdate=true;}

// Smaller unresolved ice particles fill the surrounding sheet without a solid nearby surface.
const grainN=110000,grainPos=new Float32Array(grainN*3),grainSizes=new Float32Array(grainN);
for(let i=0;i<grainN;i++){grainPos[i*3]=(rand()-.5)*4;grainPos[i*3+1]=(rand()-.5)*.022;grainPos[i*3+2]=(rand()-.5)*4;grainSizes[i]=.00035+Math.pow(rand(),3)*.0018;}
const grainGeo=new THREE.BufferGeometry();grainGeo.setAttribute('position',new THREE.BufferAttribute(grainPos,3));grainGeo.setAttribute('size',new THREE.BufferAttribute(grainSizes,1));
const grainU={uHeight:{value:innerHeight},uTime:{value:0}};
const grainMat=new THREE.ShaderMaterial({uniforms:grainU,transparent:true,depthWrite:false,vertexShader:`attribute float size;uniform float uHeight,uTime;varying float vLight;#include <logdepthbuf_pars_vertex>
void main(){vec3 p=position;p.z=mod(p.z-1.5*.00013216*p.x*uTime+2.,4.)-2.;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(size*uHeight*projectionMatrix[1][1]/max(.0001,-mv.z),.0,3.);vLight=.24+.34*fract(sin(position.x*91.+position.z*37.)*43758.);#include <logdepthbuf_vertex>}`,fragmentShader:`varying float vLight;#include <logdepthbuf_pars_fragment>
void main(){#include <logdepthbuf_fragment>
float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;gl_FragColor=vec4(vec3(.78,.82,.86)*vLight,(1.-smoothstep(.35,1.,r))*.8);}`});
const grains=new THREE.Points(grainGeo,grainMat);grains.frustumCulled=false;scene.add(grains);

// Log-depth chunks require Three's common helpers and their own preprocessor lines.
scene.traverse(o=>{if(o.material?.isShaderMaterial){const m=o.material;m.vertexShader='#include <common>\n'+m.vertexShader;m.vertexShader=m.vertexShader.replace(/(#include <[^>]+>)/g,'\n$1\n');m.fragmentShader=m.fragmentShader.replace(/(#include <[^>]+>)/g,'\n$1\n');}});
// A single render scene and a single camera: presets never exchange planet/spacecraft objects.
const sunYaw=Math.atan2(Sun.x,Sun.z);
function orbitShot(anchor,radius,yaw,pitch,roll=0,fov=38){const offset=V(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(radius);let dir=offset.clone().normalize();let u=V(-Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),-Math.cos(yaw)*Math.sin(pitch)).applyAxisAngle(dir,roll);return{eye:anchor.clone().add(offset),target:anchor.clone(),up:u,fov};}
const classics={classic:{name:'土星',en:'SATURN',caption:'同一空间 · 真实天体比例',anchor:zero,distance:7.7*R,yaw:sunYaw+.7,pitch:.38,roll:-.20,limits:{yaw:Infinity,pitch:1.45,min:.65,max:7}},wide:{name:'土星系统',en:'SATURNIAN SYSTEM',caption:'19 颗主要卫星 · JPL 历史位置',anchor:zero,distance:18*R,yaw:sunYaw+.5,pitch:.5,roll:-.15,limits:{yaw:Infinity,pitch:1.4,min:.7,max:14}},cloud:{name:'云层近景',en:'CLOUD BANDS',caption:'局部镜头 · 偏转范围 ±12°',anchor:zero,distance:2.8*R,yaw:sunYaw+.25,pitch:.25,roll:-.14,limits:{yaw:.21,pitch:.14,min:.84,max:1.12}},ring:{name:'星环特写',en:'A / B / C RINGS',caption:'A 环外缘 136,780 km · 卡西尼缝 4,833 km',anchor:V(1.68*R,0,0).applyAxisAngle(V(0,1,0),-2.2),distance:1.65*R,yaw:-1.70,pitch:.19,roll:.16,limits:{yaw:.13,pitch:.08,min:.84,max:1.10}},edge:{name:'掠过环面',en:'RING PLANE',caption:'主环典型厚度约 5–30 m · 受限掠视',anchor:zero,distance:4.9*R,yaw:sunYaw+.5,pitch:-.024,roll:-.07,limits:{yaw:.17,pitch:.018,min:.9,max:1.1}},backlit:{name:'逆光星环',en:'BACKLIT RINGS',caption:'太阳真实方向 · 微小视直径',anchor:zero,distance:8.5*R,yaw:sunYaw+Math.PI+.18,pitch:-.34,roll:.12,limits:{yaw:.20,pitch:.12,min:.85,max:1.18}},hex:{name:'北极六边形',en:'NORTH POLAR HEXAGON',caption:'北极六边形急流 · 北半球受光',anchor:V(0,RP*.77,0),distance:1.65*R,yaw:sunYaw+.2,pitch:1.37,roll:0,limits:{yaw:.18,pitch:.12,min:.85,max:1.15}},aurora:{name:'土星极光',en:'PERSISTENT POLAR AURORA',caption:'常驻极光 · 数百至约 1,500 km 高 · 可见光长曝光',anchor:V(0,-RP*.95,0),distance:.63*R,yaw:sunYaw+2,pitch:-.14,roll:0,limits:{yaw:.16,pitch:.11,min:.85,max:1.2}},ice:{name:'环粒之间',en:'CO-ORBITING ICE',caption:'冰粒 0.2–6 m · 共轨观察 · 开普勒差速',anchor:patch,distance:.050,yaw:-1.1,pitch:.26,roll:-.06,fov:58,limits:{yaw:.28,pitch:.13,min:.70,max:1.65}}};
const atmLon=sunYaw+1.17,atmLat=-3.5*DEG;const atmBase=V(Math.sin(atmLon)*R*Math.cos(atmLat),RP*Math.sin(atmLat),Math.cos(atmLon)*R*Math.cos(atmLat));const atmUp=V(atmBase.x/(R*R),atmBase.y/(RP*RP),atmBase.z/(R*R)).normalize();const atmEye=atmBase.clone().addScaledVector(atmUp,140);const atmNorth=V(-Math.sin(atmLon)*Math.sin(atmLat),Math.cos(atmLat),-Math.cos(atmLon)*Math.sin(atmLat)).normalize();
classics.ring={...classics.ice,name:'星环冰原',en:'A RING / RESOLVED ICE',caption:'A 环 · 不规则水冰颗粒 · 共轨运动'};
function currentPreset(){if(classics[state.scene])return classics[state.scene];if(state.scene==='atmos')return{name:'大气仰望',en:'ABOVE THE CLOUDS',caption:'云顶上空 · 星环真实投影 · 参考纪录片构图',limits:{yaw:Infinity,pitch:Infinity,min:.85,max:1.1},cone:80*DEG};if(state.scene==='cassini')return{name:'卡西尼—惠更斯',en:'CASSINI / SOI PERIAPSIS',caption:'2004-07-01 02:39 UTC · 首次入轨近土点历史位置',anchor:cassiniPos,distance:.029,yaw:sunYaw+.8,pitch:.27,roll:.05,limits:{yaw:Infinity,pitch:Infinity,min:.72,max:2.3}};const b=bodies[state.scene];return{name:b.name,en:state.scene.toUpperCase(),caption:state.scene==='enceladus'?'南极冰粒喷流 · 细束与稀薄散射':state.scene==='titan'?'泰坦 · 橙色有机霾 · 半径 2,574.7 km':'真实比例 · 自由环绕 / 限制观测距离',anchor:state.scene==='enceladus'?b.position.clone().add(V(0,-65,0)):b.position,distance:b.radius*(state.scene==='enceladus'?5.8:4.4),yaw:sunYaw+.35,pitch:state.scene==='enceladus'?-.28:-.12,roll:-.1,limits:{yaw:Infinity,pitch:Infinity,min:.65,max:2.1}};}
function destination(){const p=currentPreset();if(state.scene==='atmos'){const east=V().crossVectors(atmNorth,atmUp).normalize(),tilt=clamp(1.35+state.pitch,0,p.cone),azimuth=-1.318+state.yaw;const dir=coneDirection(atmUp,atmNorth,east,azimuth,tilt);const horizontal=atmNorth.clone().multiplyScalar(Math.cos(azimuth)).addScaledVector(east,Math.sin(azimuth));const u=atmUp.clone().multiplyScalar(Math.sin(tilt)).addScaledVector(horizontal,-Math.cos(tilt));return{eye:atmEye.clone(),target:atmEye.clone().addScaledVector(dir,500),up:u,fov:68/state.zoom};}let d=p.distance*state.zoom;if(innerWidth<700&&['classic','wide'].includes(state.scene))d*=Math.max(1,1.15/(innerWidth/innerHeight));return orbitShot(p.anchor,d,p.yaw+state.yaw,p.pitch+state.pitch,p.roll||0,p.fov||38);}

let pose=destination();eye.copy(pose.eye);look.copy(pose.target);up.copy(pose.up);camera.fov=pose.fov;
const obstacles=[{name:'Saturn',center:zero,axes:V(R+50,RP+50,R+50)},...Object.values(bodies).map(b=>({name:b.id,center:b.position,axes:V(b.radius*1.4,b.radius*1.4,b.radius*1.4)}))];
function startMove(){const end=destination(),d1=Math.max(.003,Math.min(eye.distanceTo(look),eye.distanceTo(cassiniPos),eye.distanceTo(patch),...Object.values(bodies).map(b=>eye.distanceTo(b.position)))),d2=end.eye.distanceTo(end.target),margin=Math.min(1000,Math.max(50,Math.min((Math.hypot(eye.x/R,eye.y/RP,eye.z/R)-1)*R,(Math.hypot(end.eye.x/R,end.eye.y/RP,end.eye.z/R)-1)*R)*.45)),flightObstacles=obstacles.map((o,i)=>i===0?{...o,axes:V(R+margin,RP+margin,R+margin)}:o),route=planRoute(eye,end.eye,flightObstacles),scale=d=>Math.max(.01,d);const logs=Math.log1p(route.length/scale(d1))+Math.log1p(route.length/scale(d2));state.transit={start:performance.now(),duration:Math.min(15000,2400+logs*430),from:{eye:eye.clone(),target:look.clone(),up:up.clone(),q:orientation(eye,look,up),fov:camera.fov},end,route,d1,d2};$('travel').classList.add('show');}
function selectShot(id){state.scene=id;state.yaw=0;state.pitch=0;state.zoom=1;startMove();updateUI();}
function updateUI(){const p=currentPreset();$('sceneName').textContent=p.name;$('sceneEnglish').textContent=p.en;$('viewCaption').textContent=p.caption;$('sceneCategory').textContent=state.scene==='cassini'?'JPL / HISTORICAL POSITION':'SATURN / PHYSICAL SCALE';document.querySelector('.intro').style.display=['classic','wide'].includes(state.scene)?'':'none';$('iceDive').hidden=true;$('iceDive').textContent=state.scene==='ice'?'返回星环特写 ↑':'下潜至冰粒之间 ↓';$('back').classList.toggle('show',state.scene!=='classic');document.querySelectorAll('[data-shot]').forEach(b=>{const on=b.dataset.shot===state.scene;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);});$('moonSelect').value=bodies[state.scene]?state.scene:'';$('viewCaption').classList.toggle('restricted',!['classic','wide'].includes(state.scene));}
function updateCamera(now,dt){const tr=state.transit;if(tr){const t=clamp((now-tr.start)/tr.duration,0,1),s=ease(t);eye.copy(tr.route.atDistance(flightDistance(t,tr.route.length,tr.d1,tr.d2)));const targetQ=orientation(eye,tr.end.target,tr.end.up);const q=tr.from.q.clone().slerp(targetQ,ease(clamp(t/.55,0,1)));up.copy(V(0,1,0).applyQuaternion(q));const focus=V(0,0,-1).applyQuaternion(q);look.copy(eye).addScaledVector(focus,mix(tr.d1,tr.d2,s));camera.fov=mix(tr.from.fov,tr.end.fov,s);$('travelFill').style.transform=`scaleX(${s})`;if(t>=1){state.transit=null;eye.copy(tr.end.eye);look.copy(tr.end.target);up.copy(tr.end.up);$('travel').classList.remove('show');}}else{const dest=destination(),f=1-Math.exp(-dt*10);const a=eye.clone().sub(dest.target),b=dest.eye.clone().sub(dest.target),ra=a.length(),rb=b.length();if(ra>1e-9&&rb>1e-9){const rot=new THREE.Quaternion().setFromUnitVectors(a.clone().normalize(),b.clone().normalize());a.normalize().applyQuaternion(new THREE.Quaternion().slerp(rot,f)).multiplyScalar(Math.exp(mix(Math.log(ra),Math.log(rb),f)));eye.copy(dest.target).add(a);}else eye.copy(dest.eye);const q=orientation(eye,look,up).slerp(orientation(eye,dest.target,dest.up),f);up.copy(V(0,1,0).applyQuaternion(q));if(state.scene==='atmos')look.copy(eye).addScaledVector(V(0,0,-1).applyQuaternion(q),500);else look.copy(dest.target);camera.fov=mix(camera.fov,dest.fov,f);}
camera.position.set(0,0,0);camera.up.copy(up);camera.lookAt(look.clone().sub(eye));let nearest=Math.min(eye.distanceTo(cassiniPos),eye.distanceTo(patch));camera.near=Math.max(.0000002,Math.min(5,nearest*.00002,eye.distanceTo(look)*.00001));camera.updateProjectionMatrix();camera.updateMatrixWorld();}
// Direction-fixed star field and a small Sun. Rendered behind all world geometry.
const screenScene=new THREE.Scene(),screenCamera=new THREE.Camera(),quadGeo=new THREE.PlaneGeometry(2,2);
const skyU={uRot:{value:new THREE.Matrix3()},uAspect:{value:1},uTan:{value:.3},uSun:{value:Sun},uGalaxy:{value:1},uResolution:{value:new THREE.Vector2()}};
const screenVert='varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}';
const skyMat=new THREE.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:skyU,vertexShader:screenVert,fragmentShader:`varying vec2 vUv;uniform mat3 uRot;uniform float uAspect,uTan,uGalaxy;uniform vec3 uSun;uniform vec2 uResolution;${common}
void main(){vec2 p=(vUv-.5)*2.;vec3 rd=normalize(uRot*vec3(p.x*uAspect*uTan,p.y*uTan,-1.));vec3 c=vec3(.0005,.0007,.0012);vec3 gn=normalize(vec3(.35,.8,-.42));float lat=dot(rd,gn),band=exp(-pow(abs(lat)*8.5,1.5));float n=fbm3(rd*8.),fine=fbm3(rd*53.),dust=fbm3(rd*19.+vec3(4,2,8));float lane=exp(-pow((lat+(dust-.5)*.08)*33.,2.));float core=pow(max(0.,dot(rd,normalize(vec3(.91,-.41,0)))),15.);vec3 milky=mix(vec3(.20,.29,.48),vec3(.68,.55,.38),clamp(core+n*.3,0.,1.));c+=uGalaxy*band*(.018+n*.055+core*.045)*milky*(1.-lane*.76)*( .58+fine*.85);
for(int layer=0;layer<2;layer++){float density=layer==0?310.:730.;vec3 cell=floor(rd*density),f=fract(rd*density)-.5;float h=hash3(cell+float(layer)*71.);vec3 jitter=vec3(hash3(cell+2.),hash3(cell+8.),hash3(cell+13.))*.58-.29;vec3 delta=f-jitter;float dist2=dot(delta,delta);float point=exp(-dist2*(layer==0?130.:170.))*step(layer==0?.975:.991,h);vec3 color=mix(vec3(.49,.68,1.),vec3(1.,.73,.45),hash3(cell+5.));c+=point*color*(layer==0?.48:.18);}
float angle=length(cross(rd,uSun)),front=step(0.,dot(rd,uSun));float px=max(.0001,uTan/uResolution.y);float disk=(1.-smoothstep(.00048-px,.00051+px,angle))*front;float glow=.000006/(angle*angle+.000011)*front;float corona=exp(-angle*65.)*.045*front;float rays=(pow(abs(sin(atan(p.y,p.x)*3.)),28.)*.015)*exp(-angle*70.)*front;c+=vec3(1.,.85,.60)*(disk*16.+glow+corona+rays);gl_FragColor=vec4(c,1.);}`});screenScene.add(new THREE.Mesh(quadGeo,skyMat));
const rt=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,depthBuffer:true});rt.samples=4;
const postScene=new THREE.Scene();const postU={tScene:{value:rt.texture},uResolution:{value:new THREE.Vector2()},uStyle:{value:0},uPrevious:{value:0},uBlend:{value:1},uExposure:{value:1.2},uEye:{value:eye},uUp:{value:V()},uSun:{value:Sun},uRot:{value:new THREE.Matrix3()},uAspect:{value:1},uTan:{value:.3},uAltitude:{value:10000},uTime:{value:0},uTitan:{value:bodies.titan.position},uSunScreen:{value:new THREE.Vector2()},uSolarVis:{value:0}};
const postMat=new THREE.ShaderMaterial({depthTest:false,depthWrite:false,uniforms:postU,vertexShader:screenVert,fragmentShader:`varying vec2 vUv;uniform sampler2D tScene;uniform vec2 uResolution;uniform float uExposure,uAspect,uTan,uAltitude,uTime,uBlend;uniform int uStyle,uPrevious;uniform vec3 uEye,uUp,uSun,uTitan;uniform vec2 uSunScreen;uniform float uSolarVis;uniform mat3 uRot;${common}

vec2 hitEllipsoid(vec3 ro,vec3 rd,vec3 center,vec3 axes){vec3 p=(ro-center)/axes,d=rd/axes;float a=dot(d,d),b=dot(p,d),h=b*b-a*(dot(p,p)-1.);if(h<0.)return vec2(-1.);float root=sqrt(h);return vec2((-b-root)/a,(-b+root)/a);}
vec4 scatterLimb(vec3 ro,vec3 rd,vec3 center,vec3 axes,float scale,vec3 tint){vec2 outer=hitEllipsoid(ro,rd,center,axes+vec3(scale*8.));if(outer.y<0.)return vec4(0.);float start=max(0.,outer.x),end=outer.y;vec2 solid=hitEllipsoid(ro,rd,center,axes);if(solid.x>0.)end=min(end,solid.x);if(end<=start)return vec4(0.);float stepLength=(end-start)/12.,trans=1.;vec3 sum=vec3(0.);float mu=dot(rd,uSun),g=.78,phase=(1.-g*g)/pow(max(.03,1.+g*g-2.*g*mu),1.5);for(int i=0;i<12;i++){vec3 p=ro+rd*(start+(float(i)+.5)*stepLength),local=p-center;float height=max(0.,(length(local/axes)-1.)*axes.x);float density=exp(-height/scale);vec3 normal=normalize(local/(axes*axes));float day=smoothstep(-.09,.20,dot(normal,uSun));float a=1.-exp(-density*stepLength/scale*.026);sum+=trans*a*tint*(.15+day*(.55+phase*.26));trans*=1.-a;}return vec4(sum,1.-trans);}

vec3 aces(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.,1.);}
vec3 style(vec3 c,int s){float lum=dot(c,vec3(.299,.587,.114));if(s==1)return floor(c*5.+.5)/5.;if(s==3){vec2 d=1./uResolution;vec3 a=texture2D(tScene,vUv+vec2(d.x,0)).rgb,b=texture2D(tScene,vUv-vec2(d.x,0)).rgb,e=texture2D(tScene,vUv+vec2(0,d.y)).rgb,f=texture2D(tScene,vUv-vec2(0,d.y)).rgb;float edge=length(a-b)+length(e-f);return vec3(.23,.74,.80)*(pow(clamp(edge*7.,0.,1.),.65)*.85+pow(lum,1.3)*.20);}return c;}
void main(){vec3 c=texture2D(tScene,vUv).rgb;vec2 p=(vUv-.5)*2.;vec3 rd=normalize(uRot*vec3(p.x*uAspect*uTan,p.y*uTan,-1.));vec4 halo=scatterLimb(uEye,rd,vec3(0.),vec3(60268.,54364.,60268.),55.,vec3(.44,.59,.82));c=c*(1.-halo.a*.55)+halo.rgb;vec4 titanHalo=scatterLimb(uEye,rd,uTitan,vec3(2574.7),38.,vec3(.80,.39,.11));c=c*(1.-titanHalo.a*.65)+titanHalo.rgb;
vec2 delta=(vUv-uSunScreen)*vec2(uAspect,1.);float flare=exp(-dot(delta,delta)*160.)*.032;float streak=exp(-abs(delta.y)*900.)*exp(-abs(delta.x)*13.)*.032;vec2 ghost=vUv-(vec2(.5)+(vec2(.5)-uSunScreen)*.62);float ghostRadius=length(ghost*vec2(uAspect,1.));float ghostRing=exp(-pow((ghostRadius-.042)/.008,2.))*.0025;c+=uSolarVis*(vec3(1.,.72,.36)*(flare+streak)+vec3(.26,.43,.55)*ghostRing);
float atmo=1.-smoothstep(180.,950.,uAltitude);
if(atmo>0.){float elev=dot(rd,uUp);float sunlight=max(0.,dot(rd,uSun));float horizon=exp(-abs(elev+.02)*5.);vec3 haze=mix(vec3(.025,.009,.003),vec3(.66,.37,.115),horizon);haze+=vec3(.65,.37,.11)*pow(sunlight,32.);c=mix(c,haze,atmo*(.30+horizon*.47));c=mix(c,haze*.65,atmo*(1.-smoothstep(-.12,-.015,elev)));
// Volumetric cloud tops below the observer, over the same oblate planet.
vec3 east=normalize(cross(vec3(0,1,0),uUp));vec3 north=normalize(cross(uUp,east));vec3 ray=vec3(dot(rd,east),dot(rd,uUp),dot(rd,north));vec3 light=vec3(dot(uSun,east),dot(uSun,uUp),dot(uSun,north));float trans=1.;vec3 clouds=vec3(0.);float start=max(2.,(uAltitude-115.)/max(.015,-ray.y));for(int i=0;i<36;i++){float t=start+float(i)*24.;vec3 q=ray*t;float h=uAltitude+q.y+(q.x*q.x+q.z*q.z)/120536.;if(h>0.&&h<125.){vec3 coord=vec3(q.x*.012,(h-35.)*.024,q.z*.012)+vec3(0,0,uTime*.000003);float n=fbm3(coord);float envelope=(1.-smoothstep(35.,120.,h))*smoothstep(-5.,20.,h);float tower=28.+110.*fbm3(vec3(q.x*.018,1.7,q.z*.018));float density=smoothstep(0.,18.,tower-h)*(.6+.4*n)*envelope;float shadow=fbm3(coord+light*.9);float l=clamp(.26+(n-shadow)*2.8+light.y*.25,.08,1.);vec3 color=mix(vec3(.20,.105,.035),vec3(.92,.70,.35),l);float a=1.-exp(-density*1.8);clouds+=trans*a*color;trans*=1.-a;if(trans<.015)break;}}c=mix(c,clouds+c*trans,atmo);}
c=pow(aces(c*uExposure),vec3(1./2.2));c=mix(style(c,uPrevious),style(c,uStyle),uBlend);c*=1.-.12*pow(length(vUv-.5),1.4);gl_FragColor=vec4(c,1.);}`});postScene.add(new THREE.Mesh(quadGeo,postMat));
function resize(){const ratio=Math.min(devicePixelRatio||1,state.quality);renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight,false);const size=renderer.getDrawingBufferSize(new THREE.Vector2());rt.setSize(size.x,size.y);postU.uResolution.value.copy(size);skyU.uResolution.value.copy(size);camera.aspect=innerWidth/innerHeight;skyU.uAspect.value=camera.aspect;postU.uAspect.value=camera.aspect;}
addEventListener('resize',resize);resize();
const labelElements={};for(const [id,b] of Object.entries(bodies)){const el=document.createElement('button');el.className='moon-tag';el.textContent=b.name;el.onclick=()=>selectShot(id);$('labels').append(el);labelElements[id]=el;}

function updateRingGuide(){const enabled=!state.transit&&(state.scene==='ring'||state.scene==='ice'||state.scene==='edge'||state.scene==='cloud'||state.scene==='classic'&&eye.length()<350000);$('ringGuide').classList.toggle('show',enabled);$('ringLocation').textContent=(state.scene==='ring'||state.scene==='ice')?'当前位于 A 环 · 距土星中心 129,500 km':'主环径向结构 · 距土星中心';}

function updateLabels(){for(const [id,b] of Object.entries(bodies)){const el=labelElements[id];let rel=b.position.clone().sub(eye);let distance=rel.length();let hidden=!state.labels||state.transit||!(['classic','wide'].includes(state.scene))||distance<b.radius*12;const v=rel.clone().project(camera);const t=-eye.dot(rel)/rel.lengthSq();if(t>0&&t<1){let point=eye.clone().addScaledVector(rel,t);if((point.x/R)**2+(point.y/RP)**2+(point.z/R)**2<1)hidden=true;}if(v.z<0||v.z>1||Math.abs(v.x)>.74||Math.abs(v.y)>.64)hidden=true;el.hidden=hidden;if(!hidden){el.style.left=(v.x*.5+.5)*innerWidth+'px';el.style.top=(-v.y*.5+.5)*innerHeight+'px';}}
}

function updateSolarFlare(){const local=Sun.clone().applyQuaternion(camera.quaternion.clone().invert());postU.uSunScreen.value.set(.5+.5*local.x/(-local.z*Math.tan(camera.fov*DEG*.5)*camera.aspect),.5+.5*local.y/(-local.z*Math.tan(camera.fov*DEG*.5)));let visible=local.z<0?1:0;for(const o of obstacles){const axes=o.name==='Saturn'?V(R,RP,R):o.axes.clone().divideScalar(1.4),p=eye.clone().sub(o.center).divide(axes),d=Sun.clone().divide(axes);const t=-p.dot(d)/d.lengthSq();if(t>0){const near=p.clone().addScaledVector(d,t).length(),angular=(near-1)*axes.x/Math.max(1,eye.distanceTo(o.center));visible*=THREE.MathUtils.smoothstep(angular,-.00052,.00052);}}postU.uSolarVis.value=visible;}

let last=performance.now();function animate(now){requestAnimationFrame(animate);if(document.hidden){last=now;return;}let dt=Math.min(.05,(now-last)/1000);last=now;if(state.playing)state.time+=dt*state.speed;updateCamera(now,dt);state.styleBlend=Math.min(1,state.styleBlend+dt*2.5);postU.uStyle.value=state.style;postU.uPrevious.value=state.oldStyle;postU.uBlend.value=state.styleBlend;
worldObjects.forEach(o=>o.object.position.copy(o.position).sub(eye));saturnRoot.rotation.y=state.time*TAU/(10.656*3600);light.position.copy(Sun).multiplyScalar(1000000);light.target.position.set(0,0,0);for(const u of uniformsToUpdate)u.uSimTime.value=state.time;
auroraUniform.uTime.value=state.time;auroraUniform.uGain.value=state.scene==='aurora'?2:1;plumeMaterials.forEach(m=>m.uniforms.uT.value=state.time);updateIce();grains.visible=ice.visible;grains.position.copy(patch).sub(eye);grainU.uTime.value=state.time;grainU.uHeight.value=renderer.domElement.height;const rot=new THREE.Matrix3().setFromMatrix4(camera.matrixWorld);skyU.uRot.value.copy(rot);postU.uRot.value.copy(rot);const tan=Math.tan(camera.fov*DEG*.5);skyU.uTan.value=tan;postU.uTan.value=tan;skyU.uGalaxy.value=state.galaxy?1:0;postU.uUp.value.copy(V(eye.x/(R*R),eye.y/(RP*RP),eye.z/(R*R)).normalize());let ell=Math.sqrt((eye.x/R)**2+(eye.y/RP)**2+(eye.z/R)**2);postU.uAltitude.value=(ell-1)*R;postU.uTime.value=state.time;postU.uExposure.value=state.scene==='hex'?1.2:state.scene==='aurora'?1.55:state.scene==='atmos'?.95:1.2;
updateSolarFlare();updateRingGuide();renderer.setRenderTarget(rt);renderer.clear();renderer.render(screenScene,screenCamera);renderer.clearDepth();renderer.render(scene,camera);renderer.setRenderTarget(null);renderer.clear();renderer.render(postScene,screenCamera);updateLabels();$('loading').classList.add('hide');const range=eye.distanceTo(currentPreset().anchor||atmEye);$('range').textContent=range<1?(range*1000).toFixed(1)+' m':Math.round(range).toLocaleString()+' km';}
await renderer.compileAsync(scene,camera);scene.traverse(o=>{if(o.material){for(const m of(Array.isArray(o.material)?o.material:[o.material]))for(const k of ['map','normalMap','roughnessMap','metalnessMap'])if(m[k])renderer.initTexture(m[k]);}});requestAnimationFrame(animate);updateUI();
let toastTimer;function toast(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2000);}
document.querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>selectShot(b.dataset.shot));document.querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{state.oldStyle=state.style;state.style=+b.dataset.style;state.styleBlend=0;document.querySelectorAll('[data-style]').forEach(x=>{let active=+x.dataset.style===state.style;x.classList.toggle('active',active);x.setAttribute('aria-pressed',active);});});
$('back').onclick=()=>selectShot('classic');$('reset').onclick=()=>selectShot(state.scene);$('universe').ondblclick=()=>selectShot(state.scene);$('iceDive').onclick=()=>selectShot(state.scene==='ice'?'ring':'ice');$('moonSelect').onchange=e=>{if(e.target.value)selectShot(e.target.value);};
$('galaxy').onclick=()=>{state.galaxy=!state.galaxy;$('galaxy').classList.toggle('on',state.galaxy);$('galaxy').setAttribute('aria-pressed',state.galaxy);};$('labelsToggle').onclick=()=>{state.labels=!state.labels;$('labelsToggle').classList.toggle('on',state.labels);$('labelsToggle').setAttribute('aria-pressed',state.labels);};function play(){state.playing=!state.playing;$('playText').textContent=state.playing?'运行中':'已暂停';$('playIcon').textContent=state.playing?'Ⅱ':'▷';$('play').setAttribute('aria-pressed',state.playing);}$('play').onclick=play;$('speed').oninput=e=>{state.speed=Number(e.target.value)*120;$('speedText').value=state.speed+'×';};$('quality').onchange=e=>{state.quality=+e.target.value;resize();};
$('clean').onclick=()=>{document.body.classList.add('clean');toast('H 显示菜单 · Esc 返回');};$('restore').onclick=()=>document.body.classList.remove('clean');$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('请在独立浏览器中使用全屏');}};$('info').onclick=()=>$('about').showModal();$('closeInfo').onclick=()=>$('about').close();
const pointers=new Map();let pinch=0;
function adjust(dx,dy){if(state.transit)return;const p=currentPreset(),lim=p.limits;let ny=state.yaw-dx,np=state.pitch+dy;if(lim.yaw!==Infinity)ny=clamp(ny,-lim.yaw,lim.yaw);if(lim.pitch!==Infinity)np=clamp(np,-lim.pitch,lim.pitch);if(p.cone)np=clamp(np,-1.35,p.cone-1.35);if(['classic','wide'].includes(state.scene))np=clamp(np,-1.45-p.pitch,1.45-p.pitch);state.yaw=ny;state.pitch=np;}
function zoom(f){if(state.transit)return;const l=currentPreset().limits;state.zoom=clamp(state.zoom*f,l.min,l.max);}
$('universe').addEventListener('pointerdown',e=>{if(state.transit){toast('镜头正在飞行，抵达后可微调');return;}$('universe').setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){const p=[...pointers.values()];pinch=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);}});
$('universe').addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;let prev=pointers.get(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===2){let p=[...pointers.values()],d=Math.hypot(p[0][0]-p[1][0],p[0][1]-p[1][1]);zoom(pinch/d);pinch=d;}else adjust((e.clientX-prev[0])*.003,(e.clientY-prev[1])*.003);});['pointerup','pointercancel','lostpointercapture'].forEach(t=>$('universe').addEventListener(t,e=>pointers.delete(e.pointerId)));$('universe').addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(clamp(e.deltaY,-100,100)*.001));},{passive:false});
addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)||$('about').open)return;if(e.key.toLowerCase()==='h')document.body.classList.toggle('clean');if(e.key==='Escape')document.body.classList.remove('clean');if(e.code==='Space'&&document.activeElement.tagName!=='BUTTON'){e.preventDefault();play();}if(e.key==='ArrowLeft')adjust(.04,0);if(e.key==='ArrowRight')adjust(-.04,0);if(e.key==='ArrowUp')adjust(0,.03);if(e.key==='ArrowDown')adjust(0,-.03);});
$('universe').addEventListener('webglcontextlost',e=>{e.preventDefault();$('loading').classList.remove('hide');$('loading').textContent='图形连接中断，请刷新页面。';});
// Read-only diagnostics are presented in the page so navigation limits and physical data are inspectable.
function diagnostics(){let p=currentPreset();$('diagnostics').textContent=JSON.stringify({version:3,shot:state.scene,inTransit:!!state.transit,yaw:state.yaw,pitch:state.pitch,zoom:state.zoom,limits:p.limits,eye:eye.toArray(),target:look.toArray(),sun:Sun.toArray(),saturnRadiusKm:R,polarRadiusKm:RP,ringOuterKm:136780,moonCount:moonSpecs.length,cassiniRadiusKm:cassiniPos.length(),epoch:'2004-07-01T02:39:00Z',lighting:'v1-art-directed',coneHalfAngle:currentPreset().cone||null,craftDistance:eye.distanceTo(cassiniPos),routeLength:state.transit?.route.length||0},null,2);requestAnimationFrame(diagnostics);}diagnostics();
